print("Enter Name: ")
x=input()
print("Enter Branch: ")
y=input()
print("Enter Gender: ")
z=input()
print("Enter College: ")
u=input()
print("Enter Age: ")
v=input()
print("Name:"+x ," Branch:" +y ,"Gender:" +z , "College:" +u ,"Age:" +v)
