u=int(input("Enter score by player 1: "))
v=int(input("Enter score by player 2: "))
w=int(input("Enter score by player 3: "))
print("Strike rate of player 1: ",u*100/60)
print("Strike rate of player 2: ",v*100/60)
print("Strike rate of player 3: ",w*100/60)
print("Score of player 1 if 60 more balls are given : ",u*2)
print("Score of player 2 if 60 more balls are given : ",v*2)
print("Score of player 3 if 60 more balls are given: ",w*2)
print("Maximum number of sixes player 1 could hit: ",u//6)
print("Maximum number of sixes player 2 could hit: ",v//6)
print("Maximum number of sixes player 3 could hit: ",w//6)
